from pathlib import Path
p=Path('web_ui/index.html')
s=p.read_text(encoding='utf-8')
repls={
'Ã„ÂÃƒÂ³ng lÃ¡Â»â€¹ch sÃ¡Â»Â­ chat':'Đóng lịch sử chat',
'Ãƒâ€”':'×',
'ChÃ¡Â»Ân kÃƒÂªnh chat':'Chọn kênh chat',
'+ Chat mÃ¡Â»â€ºi':'+ Chat mới',
'TÃƒÂ¬m trong lÃ¡Â»â€¹ch sÃ¡Â»Â­ chat':'Tìm trong lịch sử chat',
'TÃƒÂ¬m':'Tìm',
'TÃƒÂ¬m chÃ¡Â»Â§ Ã„â€˜Ã¡Â»Â...':'Tìm chủ đề...',
'GÃ¡ÂºÂ§n Ã„â€˜ÃƒÂ¢y':'Gần đây',
'NgÃ†Â°Ã¡Â»Âi dÃƒÂ¹ng':'Người dùng',
'Ã„Âang kiÃ¡Â»Æ’m tra 3 bÃ¡Â»â„¢ nÃƒÂ£o...':'Đang kiểm tra brain...',
'DÃ¡Â»Â± ÃƒÂ¡n:':'Dự án:',
'Ã¢â‚¬â€':'—',
'Ã‚Â·':'·',
'Ã¢â€ Â»':'↻',
'Refresh trÃ¡ÂºÂ¡ng thÃƒÂ¡i dÃ¡Â»Â± ÃƒÂ¡n':'Refresh trạng thái dự án',
'CÃ¡ÂºÂ¥u hÃƒÂ¬nh chat':'Cấu hình chat',
'ChÃ¡ÂºÂ¿ Ã„â€˜Ã¡Â»â„¢ AI':'Chế độ AI',
'Agent chÃ¡Â»Â§':'Agent chủ',
'Planner sÃƒÂ¢u':'Planner sâu',
'DÃ¡Â»Â±ng nÃ¡Â»â„¢i dung':'Dựng nội dung',
'PhÃ¡ÂºÂ£n biÃ¡Â»â€¡n launch':'Phản biện launch',
'CÃƒÂ´ng cÃ¡Â»Â¥':'Công cụ',
'TÃ¡Â»Â± Ã„â€˜Ã¡Â»â„¢ng':'Tự động',
'TÃ¡ÂºÂ¯t':'Tắt',
'â‹¯':'⋯',
'ThÃ†Â° viÃ¡Â»â€¡n prompt':'Thư viện prompt',
'Tráº¡ng thÃ¡i brain':'Trạng thái brain',
'Xuáº¥t chat Markdown':'Xuất chat Markdown',
'Äổi sáng/tối':'Đổi sáng/tối',
'XÃ³a chat':'Xóa chat',
'0 tin nháº¯n':'0 tin nhắn',
'NÃ¡Â»â„¢i dung trÃ¡ÂºÂ£ lÃ¡Â»Âi':'Nội dung trả lời',
'Ã„Âang trÃ¡ÂºÂ£ lÃ¡Â»Âi...':'Đang trả lời...',
'GÃ¡Â»Â­i lÃ¡ÂºÂ¡i lÃ¡Â»â€”i':'Gửi lại lỗi',
'ChÃ¡ÂºÂ¿ Ã„â€˜Ã¡Â»â„¢ trÃ¡ÂºÂ£ lÃ¡Â»Âi':'Chế độ trả lời',
'FAST: topK thÃ¡ÂºÂ¥p, khÃƒÂ´ng benchmark/export':'FAST: topK thấp, không benchmark/export',
'BALANCED: dÃƒÂ¹ng skill + brain vÃ¡Â»Â«a Ã„â€˜Ã¡Â»Â§':'BALANCED: dùng skill + brain vừa đủ',
'DEEP: chÃ¡ÂºÂ­m hÃ†Â¡n, dÃƒÂ¹ng nhiÃ¡Â»Âu RAG/audit/export':'DEEP: chậm hơn, dùng nhiều RAG/audit/export',
'Ã„ÂiÃ¡Â»Âu hÃ†Â°Ã¡Â»â€ºng cÃƒÂ¢u hÃ¡Â»Âi vÃƒÂ  cÃƒÂ¢u trÃ¡ÂºÂ£ lÃ¡Â»Âi':'Điều hướng câu hỏi',
'LÃƒÂªn cÃƒÂ¢u hÃ¡Â»Âi/cÃƒÂ¢u trÃ¡ÂºÂ£ lÃ¡Â»Âi trÃ†Â°Ã¡Â»â€ºc':'Lên câu hỏi trước',
'XuÃ¡Â»â€˜ng cÃƒÂ¢u hÃ¡Â»Âi/cÃƒÂ¢u trÃ¡ÂºÂ£ lÃ¡Â»Âi tiÃ¡ÂºÂ¿p theo':'Xuống câu hỏi tiếp theo',
'Ã¢â€ â€˜':'↑',
'Ã¢â€ â€œ':'↓',
'Ã„ÂÃƒÂ­nh kÃƒÂ¨m file':'Đính kèm file',
'Nháº­p cÃ¢u há»i, dÃ¡n áº£nh, hoáº·c kÃ©o file vÃ o Ä‘Ã¢y...':'Nhập câu hỏi, dán ảnh, hoặc kéo file vào đây...',
'Gá»­i':'Gửi',
'âž¤':'➤',
'Canvas kÃ¡ÂºÂ¿t quÃ¡ÂºÂ£':'Canvas kết quả',
'Ã¢Â§â€°':'⧉',
'TÃ¡ÂºÂ£i Markdown':'Tải Markdown',
'Ã„ÂÃƒÂ³ng canvas':'Đóng canvas',
}
for a,b in repls.items():
    s=s.replace(a,b)
s=s.replace('v1.14-vendor-ready-builder.5','v1.14-vendor-ready-builder.6').replace('v=1.14-vendor-ready-builder.5','v=1.14-vendor-ready-builder.6').replace('v=1.14-vendor-ready-builder.4','v=1.14-vendor-ready-builder.6')
p.write_text(s, encoding='utf-8')
Path('VERSION').write_text('v1.14-vendor-ready-builder.6\n', encoding='utf-8')
